### ISSUE TITLE
Schema errors during compilation

### ISSUE THREAD

**Issue by kubasub** [danschultzer/ex_oauth2_provider#46]
I'm getting an error with `ExOauth2Provider.OauthApplications.create_application/2`:
```
iex> oauth_application_owner = # Load MyApp.Schemas.OauthApplicationOwner
iex> ExOauth2Provider.OauthApplications.create_application(oauth_application_owner, %{
...>   name: "Oauth Application",
...>   uid: "3957adf55f16h4c88f6388d4c57357743556d7999de4ca217d5bb3e782e10726",
...>   secret: "c5604029e13afbe60ff9e7a3c6545337d7f5e9ab18dbc58ec1bbd191106afffd",
...>   redirect_uri: "https://example.com/callback_uri"
...> })
INSERT INTO "oauth_application_owners" ("name","inserted_at","updated_at","id") VALUES ($1,$2,$3,$4) ["An Application Owner", #DateTime<2019-02-28 22:20:34.400424Z>, #DateTime<2019-02-28 22:20:34.400424Z>, <<9, 63, 103, 221, 248, 34, 65, 212, 151, 146, 194, 143, 4, 23, 17, 234>>]
** (UndefinedFunctionError) function nil.__schema__/1 is undefined
    nil.__schema__(:primary_key)
    (ecto) lib/ecto/changeset/relation.ex:140: Ecto.Changeset.Relation.change/3
    (ecto) lib/ecto/changeset.ex:1132: Ecto.Changeset.put_change/7
    (ecto) lib/ecto/changeset.ex:1339: Ecto.Changeset.put_relation/5
    (ex_oauth2_provider) lib/ex_oauth2_provider/oauth_applications/oauth_applications.ex:244: ExOauth2Provider.OauthApplications.new_application_changeset/3
    (ex_oauth2_provider) lib/ex_oauth2_provider/oauth_applications/oauth_applications.ex:145: ExOauth2Provider.OauthApplications.create_application/2
    priv/repo/seeds.exs:46: (file)
```

From some digging, it seems as though `ex_oauth2_provider` isn't getting compiled correctly.

### Troubleshooting

When compiling `ex_oauth2_provider` as a dependency in my project, I get this output:
```
==> ex_oauth2_provider
Compiling 37 files (.ex)

12:57:56.296 [error] You need to set a resource_owner or application_owner in your config and recompile ex_oauth2_provider!
warning: invalid association `resource_owner` in schema ExOauth2Provider.OauthAccessGrants.OauthAccessGrant: associated schema nil does not exist
  lib/ex_oauth2_provider/oauth_access_grants/oauth_access_grant.ex:1: ExOauth2Provider.OauthAccessGrants.OauthAccessGrant (module)

warning: invalid association `resource_owner` in schema ExOauth2Provider.OauthAccessTokens.OauthAccessToken: associated schema nil does not exist
  lib/ex_oauth2_provider/oauth_access_tokens/oauth_access_token.ex:1: ExOauth2Provider.OauthAccessTokens.OauthAccessToken (module)

warning: invalid association `owner` in schema ExOauth2Provider.OauthApplications.OauthApplication: associated schema nil does not exist
  lib/ex_oauth2_provider/oauth_applications/oauth_application.ex:1: ExOauth2Provider.OauthApplications.OauthApplication (module)

Generated ex_oauth2_provider app
```

When running the project, it seems that `ex_oauth2_provider` does not get compiled correctly.

```ex
iex> ExOauth2Provider.OauthApplications.OauthApplication.__schema__(:association, :owner)
%Ecto.Association.BelongsTo{
  cardinality: :one,
  defaults: [],
  field: :owner,
  on_cast: nil,
  on_replace: :raise,
  owner: ExOauth2Provider.OauthApplications.OauthApplication,
  owner_key: :owner_id,
  queryable: nil, # <-- NOTICE THIS
  related: nil, # <---- AND THIS
  related_key: :id,
  relationship: :parent,
  unique: true,
  where: []
}
```

After deleting `_build/prod/lib/ex_oauth2_provider` and running iex again:
```ex
iex> ExOauth2Provider.OauthApplications.OauthApplication.__schema__(:association, :owner)
%Ecto.Association.BelongsTo{
  cardinality: :one,
  defaults: [],
  field: :owner,
  on_cast: nil,
  on_replace: :raise,
  owner: ExOauth2Provider.OauthApplications.OauthApplication,
  owner_key: :owner_id,
  queryable: MyApp.Schemas.OauthApplicationOwner,
  related: MyApp.Schemas.OauthApplicationOwner,
  related_key: :id,
  relationship: :parent,
  unique: true,
  where: []
}
```

The functions works the first time I compile locally, but it doesn't work in my prod environment until I delete that build directory and recompile. I'm unable to find the different between the two environments.

Could this have to do with the upgrade to Ecto 3? Any ideas?

Thanks in advance, and thanks for making this package!

**Comment by danschultzer** [comment]
This is what causes the error:

https://github.com/danschultzer/ex_oauth2_provider/blob/b3fe5a5d8cb526798e11338c60cbabf8f7a22eda/lib/ex_oauth2_provider/oauth_applications/oauth_application.ex#L18

It'll fail if it doesn't have access to the environment config when it's compiling since it's needed in that macro call.

I'll have to fix this probably at some point, ideally `:ex_oauth2_provider` should generate schema modules for your project rather than having compiling it.

**Comment by kubasub** [comment]
> It'll fail if it doesn't have access to the environment config when it's compiling since it's needed in that macro call.

That was the exact issue. As I said, locally it worked fine, but there was an issue with how we were setting up our prod environment where we didn't copy over the config file before compiling!

Thanks for the help!
