### ISSUE TITLE
`Mix.env/0 is undefined` in `ExOauth2Provider.Config.force_ssl_in_redirect_uri?`

### ISSUE THREAD

**Issue by 0x6a6f74726f** [danschultzer/ex_oauth2_provider#71]
Hey. Within our production environment (via `mix release`) i get an error regarding `Mix.env is undefined` (which is  obviously not available).

Log:
```
Request: POST /settings/applications
** (exit) an exception was raised:
    ** (UndefinedFunctionError) function Mix.env/0 is undefined (module Mix is not available)
        Mix.env()
        (ex_oauth2_provider) lib/ex_oauth2_provider/config.ex:120: ExOauth2Provider.Config.force_ssl_in_redirect_uri?/1
        (ex_oauth2_provider) lib/ex_oauth2_provider/redirect_uri.ex:40: ExOauth2Provider.RedirectURI.invalid_ssl_uri?/2
        (ex_oauth2_provider) lib/ex_oauth2_provider/redirect_uri.ex:32: ExOauth2Provider.RedirectURI.do_validate/3
        (ex_oauth2_provider) lib/ex_oauth2_provider/applications/application.ex:109: anonymous fn/3 in ExOauth2Provider.Applications.Application.validate_redirect_uri/2
        (elixir) lib/enum.ex:1948: Enum."-reduce/3-lists^foldl/2-0-"/3
        (ex_oauth2_provider) lib/ex_oauth2_provider/applications/application.ex:75: ExOauth2Provider.Applications.Application.changeset/3
        (ex_oauth2_provider) lib/ex_oauth2_provider/applications/applications.ex:159: ExOauth2Provider.Applications.create_application/3
```

Configuration

```
config :core, ExOauth2Provider, force_ssl_in_redirect_uri: true
```

**Comment by 0x6a6f74726f** [comment]
fixed by update to version: `0.5.5`
